language: node_js
node_js:
  - lts/*
env: ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true YARN_GPG=no CC=clang CXX=clang++ npm_config_clang=1
jobs:
  fast_finish: true
  include:
    - os: windows
      compiler: clang
    - os: osx
      env: ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true YARN_GPG=no CC=gcc-4.9 CXX=g++-4.9 npm_config_clang=1
      osx_image: xcode12.2
      before_install: 
          - brew install git-lfs
          - brew install openssl
          - brew install gcc49
    - os: linux
      before_install: sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
      env: ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true YARN_GPG=no
      compiler: clang
cache:
  - npm
  - yarn
  - directories:
    - node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"
install:
  - npm install -g xvfb-maybe
  - yarn
script:
  - yarn electron:build
branches:
  only:
    - main
