language: node_js
node_js:
  - lts/*
env: ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true YARN_GPG=no CC=clang CXX=clang++ npm_config_clang=1
jobs:
  fast_finish: true
  include:
    - os: windows
      compiler: clang
    - os: osx
      osx_image: xcode12.2
      before_install: 
        - brew install git-lfs
    - os: linux
      before_install: sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils
      env: ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true YARN_GPG=no
      compiler: clang
  allow_failures:
    - os: osx
cache:
  - npm
  - yarn
  - directories:
    - node_modules
    - "$HOME/.electron"
    - "$HOME/.cache"
install:
  - npm install -g xvfb-maybe
  - yarn
script:
  - yarn electron:build
branches:
  only:
    - main
